-- server only
if not isServer() then return end

local Loader = require "Injectors/Utils/Loader"
local Hemostatic = {}

Loader.Populate(Hemostatic, "HEMOSTATIC",
{
    "MEND_BLEEDING_ENABLED",
    "MEND_BLEEDING_RATE",
    "MEND_BLEEDING_DELAY",
    "MEND_BLEEDING_DURATION",
    "MEND_BLEEDING_BASE_REDUCTION",

    "MEND_DEEP_WOUND_ENABLED",
    "MEND_DEEP_WOUND_RATE",
    "MEND_DEEP_WOUND_DELAY",
    "MEND_DEEP_WOUND_DURATION",
    "MEND_DEEP_WOUND_BASE_REDUCTION",

    "OVERDOSE_ENABLED",
    "OVERDOSE_PENALTY",
    "OVERDOSE_DELAY",

    "HUNGER_ENABLED",
    "HUNGER_DELAY",
    "HUNGER_RATE",
    "HUNGER_DURATION",
    "HUNGER_BASE_PENALTY",

    "THIRST_ENABLED",
    "THIRST_DELAY",
    "THIRST_RATE",
    "THIRST_DURATION",
    "THIRST_BASE_PENALTY"
},
-- bodyparts
{
    BLEEDING_COEFFICIENTS = "MEND_BLEEDING_COEFFICIENT",
    DEEPWOUND_COEFFICIENTS = "MEND_DEEP_WOUND_COEFFICIENT"
})

return Hemostatic