-- server only
if not isServer() then return end

local Loader = require "Injectors/Utils/Loader"
local Propital = {}

Loader.Populate(Propital, "PROPITAL",
{
    "FLAT_HEALING_ENABLED",
    "FLAT_HEALING_RATE",
    "FLAT_HEALING_DELAY",
    "FLAT_HEALING_DURATION",
    "FLAT_HEALING_BASE_ADDITION",
    "FLAT_HEALING_MIN_LINEAR_RANGE",
    "FLAT_HEALING_MAX_LINEAR_RANGE",
    "FLAT_HEALING_MIN_LINEAR_SCALE",
    "FLAT_HEALING_MAX_LINEAR_SCALE",

    "OVERDOSE_ENABLED",
    "OVERDOSE_PENALTY",
    "OVERDOSE_DELAY",

    "HUNGER_ENABLED",
    "HUNGER_DELAY",
    "HUNGER_RATE",
    "HUNGER_DURATION",
    "HUNGER_BASE_PENALTY",

    "THIRST_ENABLED",
    "THIRST_DELAY",
    "THIRST_RATE",
    "THIRST_DURATION",
    "THIRST_BASE_PENALTY"
})

return Propital